// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "fce7da0d-e01b-4d2e-bcf4-9e9fa89dc2c7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1532704695);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1532704815);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1532703960);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1532704575);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1532705055);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1532704455);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1532449906);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1532704935);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1532445513);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a16bb057-a9f2-4e17-9609-5a9b16147f7a}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1532581200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1532704935);
user_pref("browser.onboarding.notification.prompt-count", 2);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1532703932932");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1532705752932");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1532703933316");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1532707533316");
user_pref("browser.search.countryCode", "MX");
user_pref("browser.search.region", "MX");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180507144241");
user_pref("browser.slowStartup.averageTime", 863);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20180507144241");
user_pref("browser.startup.homepage_override.mstone", "60.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1532445519189");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Tue, 24 Jul 2018 09:24:46 GMT");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1532704696);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180507144241");
user_pref("extensions.lastAppVersion", "60.0");
user_pref("extensions.lastPlatformVersion", "60.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"e7c12eeb-3ac3-4b8c-a7ca-8cc73675f882\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1532704623);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1532704697);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180507144241");
user_pref("media.gmp-manager.lastCheck", 1532617882);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1532449900);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "8de1a9c4-3fe2-463d-8fc2-6d09399e99b9");
user_pref("services.blocklist.addons.checked", 1532704791);
user_pref("services.blocklist.clock_skew_seconds", 24);
user_pref("services.blocklist.gfx.checked", 1532704791);
user_pref("services.blocklist.last_etag", "\"1532704364007\"");
user_pref("services.blocklist.last_update_seconds", 1532704791);
user_pref("services.blocklist.onecrl.checked", 1532704791);
user_pref("services.blocklist.pinning.checked", 1532704791);
user_pref("services.blocklist.plugins.checked", 1532704791);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1532449900);
user_pref("toolkit.startup.last_success", 1532703930);
user_pref("toolkit.telemetry.cachedClientID", "f9745154-81ff-4513-b1b6-28a6d520c09f");
user_pref("toolkit.telemetry.previousBuildID", "20180507144241");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
